# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import emotion_types.emotion_speech_service_pb2 as emotion__speech__service__pb2


class EmotionSpeechServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeEmotion = channel.unary_unary(
                '/emotion_speech.v1.EmotionSpeechService/RecognizeEmotion',
                request_serializer=emotion__speech__service__pb2.AudioRequest.SerializeToString,
                response_deserializer=emotion__speech__service__pb2.EmotionResponse.FromString,
                )


class EmotionSpeechServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeEmotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionSpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeEmotion': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeEmotion,
                    request_deserializer=emotion__speech__service__pb2.AudioRequest.FromString,
                    response_serializer=emotion__speech__service__pb2.EmotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotion_speech.v1.EmotionSpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmotionSpeechService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeEmotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emotion_speech.v1.EmotionSpeechService/RecognizeEmotion',
            emotion__speech__service__pb2.AudioRequest.SerializeToString,
            emotion__speech__service__pb2.EmotionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
