# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: emotion_speech_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65motion_speech_service.proto\x12\x11\x65motion_speech.v1\"\x1d\n\x0c\x41udioRequest\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\"\n\x0f\x45motionResponse\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t2q\n\x14\x45motionSpeechService\x12Y\n\x10RecognizeEmotion\x12\x1f.emotion_speech.v1.AudioRequest\x1a\".emotion_speech.v1.EmotionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emotion_speech_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOREQUEST']._serialized_start=51
  _globals['_AUDIOREQUEST']._serialized_end=80
  _globals['_EMOTIONRESPONSE']._serialized_start=82
  _globals['_EMOTIONRESPONSE']._serialized_end=116
  _globals['_EMOTIONSPEECHSERVICE']._serialized_start=118
  _globals['_EMOTIONSPEECHSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
